language: go

go:
  - 1.15.x
  - master

script:
  - cd server
  - go test 
  - cd ..

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: html
    on:
      branch: master