language: go

go:
  - 1.15.x
  - master

go_import_path: https://github.com/Rigry/tcp_server.git

script: 
  - go test -v -coverprofile=cover.out
  - mkdir ./html
  - go tool cover -html=cover.out -o ./html/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: html
    on:
      branch: master